### ISSUE TITLE
Scrollable Conversation?

### ISSUE THREAD

**Issue by ghost** [sevenleaps/chat-template#10]
Hello! our company uses this for the chat implementation of our project. One thing that we do not like about (sorry!) is the part where the oldest message is being overlapped by the parent div. Is there a way to fix this issue? Thanks.

**Comment by paulofla** [comment]
Hi @Timmerdev 

Thanks for opening an issue!

Can you provide a code example of what you don't like versus what you would like and why?

Thanks,
Paul

**Comment by paulofla** [comment]
Hi @Timmerdev 

I'm not sure I fully understand this part of what you are saying:
`the part where the oldest message is being overlapped by the parent div.`

Do you mean that you can't view messages that have gone past the height of the chat screen? Like say the [Earth message in this story.](http://sevenleaps.github.io/chat-template/?selectedKind=Conversation&selectedStory=Conversation%20configured%20to%20start%20with%20a%20history%20of%20messages%2C%20turning%20the%20loop%20off)

Either way to make the conversation scrollable will require a good bit of work.

I'll try to add scrolling this week and report back if it's too much.

Thanks,
Paul

**Comment by paulofla** [comment]
This should be added in the 0.0.26 release.

It's a temporary fix and is only supported with my mousewheel on a mac.

I'm going to add a v1 milestone that will include scrolling as a goal.
