### ISSUE TITLE
Control height of conversation component inside chat

### ISSUE THREAD

**Issue by vibhanshuc** [sevenleaps/chat-template#11]
I am using [chat](http://sevenleaps.github.io/chat-template/?selectedKind=Chat&selectedStory=Chat%20configured%20to%20end%20at%20the%20last%20message%20and%20allows%20the%20user%20to%20add%20messages) component 

```html
<Chat styles={styles} messages={messagesForConversation}/>
```

styles object is as follows:

```js
styles = {
      chat: {
        height: '800px'
      }
    }
```

But this just increases the height of chat div, but there is no way to increase the height of Conversation component inside it.  Can you please let me know if it can be achieved anyhow?

Chat-Template: 0.0.24
React: 15.4.2
Chrome: 56.0.2924.87

**Comment by paulofla** [comment]
Hi @vibhanshuc 

Thank you for opening this issue.

I'll have a look into this and report back later today.

Thanks,
Paul

**Comment by paulofla** [comment]
Hi @vibhanshuc 

I've added a fix for this. Please update to the latest version and see if that fixes your issue.

In the meantime, I'll close this issue out.

Example code:
``` js
const styles = {
    chat: {
      height: '480px',
    },
    conversation: {
      height: '400px',
    },
    container: {
      bottom: '1%',
    },
    messages: {
      height: '99%',
    },
    noTyping: {
      height: '2%',
    },
    textInputContainer: {
      height: '80px',
    },
    textInput: {
      fontSize: '2em',
    },
  };
  return (
    <div>
      <Chat historicMessages={historicMessages} messages={messagesForConversation} turnOffLoop styles={styles} />
    </div>
  );
```

An example storybook of it is located in the [Chat component here](http://sevenleaps.github.io/chat-template/?selectedKind=Chat&selectedStory=Chat%20configured%20styles%20and%20ends%20at%20the%20last%20message%20and%20allows%20the%20user%20to%20add%20messages)

Thanks,
Paul
