### ISSUE TITLE
Messages disappear in Conversation (help wanted)

### ISSUE THREAD

**Issue by Hosar** [sevenleaps/chat-template#3]
Hi, when using <Conversation height={300} messages={messages} /> component it works really fine.
But could be possible to do not disappear the messages after some duration?
I have tried with `duration:0` and `duration:-1`, but still the messages disappear and after some time become visible again.

Is this feature supported?

```
const messages = [{
            message: 'How do I use this messaging app?',
            from: 'right',
            backColor: '#3d83fa',
            textColor: 'white',
            avatar: 'https://www.seeklogo.net/wp-content/uploads/2015/09/google-plus-new-icon-logo.png',            
            duration:0,
            inbound: true,
        }];
```

**Comment by paulofla** [comment]
Hi Hosar,

No, this feature is not **yet** supported. [See this StackOverflow for negative delays](http://stackoverflow.com/questions/8430966/is-calling-settimeout-with-a-negative-delay-ok) (Essentially a browser has a non-negative minimum amount of time to run a timeout)

When we made this package, our use case was to have the messages reappear after a certain time. As such, we have set a default duration of 800 ms. (Line 90 in Conversation.js)

I'll have a look at this later today to try and add this functionality in.

Thanks,
Paul

**Comment by Hosar** [comment]
ok @paulofla thank you anyway.

**Comment by paulofla** [comment]
@Hosar I've added this feature into https://github.com/sevenleaps/chat-template/pull/4

**Comment by paulofla** [comment]
Closing issue as the solution has now been merged to master
