### ISSUE TITLE
Some render issue

### ISSUE THREAD

**Issue by vvinton** [sevenleaps/chat-template#6]
Folks, not sure how precisely explain - 

During initial rendering of message history, render happens pretty well:
`<Conversation turnOffLoop messages={msgs}/>;`

But when msgs object gets updated (say, new element added to it), rendering does not seems happening - I see only old messages.

Vitaliy

**Comment by paulofla** [comment]
Hi @vvinton 

Thank you for opening up this issue!

I'll add the ability to add a new message after the messages have loaded later today.

Thanks,
Paul

**Comment by vvinton** [comment]
hi Paul - thank you for respose - what I observed additionally - when the next time component created (i.e. Conversation) - new message pops up. In other word - with now:
`<Conversation turnOffLoop messages={msgs}/>;` - loads history
if to create (in on render method component again) as:
`<Conversation turnOffLoop messages={newSingleMessage}/>;` - it will be appropriatelly added to history - in other words previous and new message will appear.

**Comment by paulofla** [comment]
HI @vvinton 

Sorry, I've been busy the last few days so I haven't had a chance to fix/look at this issue.

Can you please create a working code example for the original issue and the issue above?

In your example above does it go through `msgs` and display the animation for it and then do you: Change the messages parameter to a different object called `newSingleMessage` that contains only one message and that plays the animation to add it to the chat with the history still there?
OR
Are you adding `newSingleMessage` to the original `msgs` object and it is adding it to the chat successfully?

I'll have a look at this tonight.

Thanks,
Paul

**Comment by paulofla** [comment]
Apologies that it took me over a week to deliver the fix for this. I wasn't able to work on this issue until tonight.

I've created a `Chat` story in storybook. You should be able to add messages and they will display now. I've fixed this issue in the latest release.

Please update to the latest release and let me know if this fixes this issue.

In the meantime, I will close out this issue.
