### ISSUE TITLE
Help/Question generating conversation

### ISSUE THREAD

**Issue by devgripes** [sevenleaps/chat-template#9]
I really liked how the messages can be displayed in one full json type.

I'm wondering if, would it be possible to generate `<Conversation>` then wait for the user's actual response before proceeding to the next message?

Like for example
```
const conversationMessage = [
  {typing...},
  {message (wait for reply before show typing)...},
  {typing...},
  {message...},
  {typing...},
  {message...}
]
```

Any inputs are appreciated, thanks :)

**Comment by paulofla** [comment]
Hi @kuronaru 

If you update to the latest version of chat template, I've added this functionality but you have to add to the original messages object as needed.

```javascript
const messages = [
    {
      message: 'Please enter a message',
      inbound: true,
      backColor: 'white',
      duration: 1000,
    }
  ];

const messagesAfterUserInput = [
    {
      message: 'After user message 1',
      inbound: true,
      backColor: 'white',
      duration: 1000,
    },
    {
      message: 'After user message 2',
      inbound: true,
      backColor: 'white',
      duration: 1000,
    }
  ];
let index = 0;
      <Conversation messages={messages} turnOffLoop />

```

After a user input:

```javascript
const userMessage = getUserMessage();
this.messages.push(userMessage);
this.messages.push(this.messagesAfterUserInput[index]);
index++;
```
This will add the users message to the conversation and then the message you want to display after the user input.

If you look at the Chat React element and the Chat story in storybook you can hopefully see what I'm trying to say here.

Let me know if this doesn't make sense as I wrote this response quickly.

Thanks,
Paul

**Comment by paulofla** [comment]
Hi @kuronaru

I hope that made sense.

I'm going to close out this issue. Please reopen if you have any further questions.

Thanks,
Paul
